// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6LdnrzWa8X9BdmtsgIxzUjyIEWknaIs',
    appId: '1:813444113058:web:abf86aa244fc5f97baadfb',
    messagingSenderId: '813444113058',
    projectId: 'chatdong-edd7c',
    authDomain: 'chatdong-edd7c.firebaseapp.com',
    storageBucket: 'chatdong-edd7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiXV2tLNWA2Xp2iXnBpZnhSsJ2ZKMOK_k',
    appId: '1:813444113058:android:bc9de18d13626ecbbaadfb',
    messagingSenderId: '813444113058',
    projectId: 'chatdong-edd7c',
    storageBucket: 'chatdong-edd7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi6Ob-fpf88q_7fqTrWVuXlumYWL4USSI',
    appId: '1:813444113058:ios:3081a5c38cbae541baadfb',
    messagingSenderId: '813444113058',
    projectId: 'chatdong-edd7c',
    storageBucket: 'chatdong-edd7c.appspot.com',
    iosClientId: '813444113058-n8q5hf3e4qukuhdblfk0hp35l63fmf4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi6Ob-fpf88q_7fqTrWVuXlumYWL4USSI',
    appId: '1:813444113058:ios:3081a5c38cbae541baadfb',
    messagingSenderId: '813444113058',
    projectId: 'chatdong-edd7c',
    storageBucket: 'chatdong-edd7c.appspot.com',
    iosClientId: '813444113058-n8q5hf3e4qukuhdblfk0hp35l63fmf4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
